# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
# Imported from Arclight
    - name: Cache gradle user files
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: Linux-gradle-user-home
      env:
        JAVA_HOME_8.0.312_x64: /opt/hostedtoolcache/jdk/8.0.312/x64
        JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.312/x64
        JAVA_HOME_8_0_312_X64: /opt/hostedtoolcache/jdk/8.0.312/x64
    - name: Cache gradle files
      uses: actions/cache@v1
      with:
        path: ./.gradle
        key: Linux-gradle-file
      env:
        JAVA_HOME_8.0.312_x64: /opt/hostedtoolcache/jdk/8.0.312/x64
        JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.312/x64
        JAVA_HOME_8_0_312_X64: /opt/hostedtoolcache/jdk/8.0.312/x64
    - name: Grant permission
      run: chmod -x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build --no-daemon -i --stacktrace
        cache-disabled: false
        cache-read-only: false
        gradle-home-cache-includes: caches
# Imported from WorldEdit's script
    - uses: actions/upload-artifact@v2.2.4
      name: Archive Reports
      if: always()
      with:
        name: reports for ${{ matrix.os }}
        path: '**/build/reports/**'
