# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Build

on:
  push:
    branches: [ "Experiment(pre-Alpha)" ]
  pull_request:
    branches: [ "Experiment(pre-Alpha)" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

# This part is experimental.
    - name: Cache Gradle User Files
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
        
# This part is experimental.
    - name: Cache Gradle Files
      uses: actions/cache@v1
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
    
    - name: Grant permission
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        ./gradlew build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "Armourers-Workshop"
        path: ./build/libs/*.jar
